services:
  aufgaben-meister-db:
    image: postgres:latest
    container_name: aufgaben-meister-db
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - aufgaben-meister-networks
    volumes:
      - aufgaben-meister-dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  aufgaben-meister-pooling:
    image: edoburu/pgbouncer:latest
    container_name: aufgaben-meister-pooling
    restart: no
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: aufgaben-meister-db
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    networks:
      - aufgaben-meister-networks
    ports:
      - "6432:6432"
    depends_on:
      aufgaben-meister-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-h",
          "aufgaben-meister-pooling",
          "-p",
          "6432",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  aufgaben-meister-redis:
    image: redis:latest
    container_name: aufgaben-meister-redis
    restart: no
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - aufgaben-meister-networks
    volumes:
      - aufgaben-meister-redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  aufgaben-meister-networks:

volumes:
  aufgaben-meister-dbdata:
  aufgaben-meister-redisdata:
